### ISSUE TITLE
Bug: branch not protected error

### ISSUE THREAD

**Issue by brianamarie** [githubtraining/innersource#26]
Initial error message found: https://github.com/brianamarie/innersource/issues/6

```
#### This issue is used for debugging errors thrown during a course.

---

* Node.js Version: `v10.16.3`
* Node.js Env: `production`
* Git SHA: `53dccff264e8d8d6bf51523c183e511a1b873da1`
* Git Branch: `improve-api-docs`

---

###### Seeing a problem? Open an issue [in the course repository](https://github.com/githubtraining/innersource/issues/new).
```

> #### Error in innersource-fundamentals:answer-the-workflows-challenge-question:removeBranchProtection[0]

```
HttpError: {"message":"Branch not protected","documentation_url":"https://developer.github.com/v3/repos/branches/#remove-branch-protection"}
    at response.text.then.message (/app/node_modules/@octokit/rest/lib/request/request.js:72:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

cc @hectorsector

**Comment by a-a-ron** [comment]
Hey, @brianamarie. Thanks for opening this issue. I'm not getting this error anymore. We remove the branch protection as stated in the config file and if the user refreshed the page then they don't see the restriction anymore. If they don't refresh the page, they can approve the request to then merge. Either way, the course progresses as expected. I went through it twice and wasn't able to recreate this error so I think we are good to close this out. Re-open if needed.

**Comment by hectorsector** [comment]
To help with issues like this in the future, we should mark the removal or enabling of branch protections optional (see this commit for [an example](https://github.com/githubtraining/innersource/commit/1cc95d851b9752746133a3f9faa6df7999d9819c)). The flow that calls for this is:
1. The learner removed their own branch protections (exploring is encouraged)
2. The bot attempts to remove branch protections
3. The API returns an error because the branch is not protected 
4. The course errors out and stops working. 

Adding the required:false flag makes it so that the error doesn't block the course. 

We should also add this to our authoring/style docs as a best practice.

**Comment by brianamarie** [comment]
👍 Sounds good. I will add that info to a card in the documentation column.
